<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OutputPath>../out/renderer</OutputPath>
		<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>
	<PropertyGroup>
		<DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(appdata)/XIVLauncher/addon/Hooks/dev/</DalamudLibPath>
		<DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('Linux'))">$(HOME)/.xlcore/dalamud/Hooks/dev/</DalamudLibPath>
		<DalamudLibPath Condition="$([MSBuild]::IsOSPlatform('OSX'))">$(HOME)/Library/Application Support/XIV on Mac/dalamud/Hooks/dev/</DalamudLibPath>
		<DalamudLibPath Condition="$(DALAMUD_HOME) != ''">$(DALAMUD_HOME)/</DalamudLibPath>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="../Browsingway.Common/Browsingway.Common.csproj"/>
		<Reference Include="TerraFX.Interop.Windows">
			<HintPath>$(DalamudLibPath)TerraFX.Interop.Windows.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31"/>
		<PackageReference Include="SharedMemory" Version="2.3.2"/>
	</ItemGroup>
	<Target Name="RemoveUnusedWebView2WpfReference" BeforeTargets="ResolveAssemblyReferences">
		<ItemGroup>
			<Reference Remove="@(Reference)" Condition="'%(Reference.Filename)%(Reference.Extension)' == 'Microsoft.Web.WebView2.Wpf.dll'"/>
		</ItemGroup>
	</Target>
	<PropertyGroup Condition="'$(GITHUB_ACTIONS)' == ''">
		<DalamudLibPath>$(appdata)/XIVLauncherCN/addon/Hooks/dev</DalamudLibPath>
		<AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
	</PropertyGroup>
</Project>
